package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("admin", "id", Admin.class);
		arp.addMapping("department", "id", Department.class);
		arp.addMapping("rate", "id", Rate.class);
		arp.addMapping("rules", "id", Rules.class);
		arp.addMapping("student", "id", Student.class);
	}
}

