package com.demo.common.model;

import com.demo.common.model.base.BaseDepartment;

import java.util.List;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Department extends BaseDepartment<Department> {
	public static final Department dao = new Department().dao();

	public List getsDepartment(){
		return Department.dao.find("select * from department");
	}

	public boolean insertDepartment(String department) {
		return new Department().set("department",department).save();
	}

	public boolean updateDepartment(int id,String department) {
		return Department.dao.findById(id).setDepartment(department).update();
	}

	public boolean deleteDepartment(int id){
		return Department.dao.findById(id).delete();
	}

}
