package com.demo.common.model;

import com.demo.common.model.base.BaseRate;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rate extends BaseRate<Rate> {
	public static final Rate dao = new Rate().dao();

	public List getRate(){
		return Rate.dao.find("select * from rate");
	}

	public boolean insertRate(int rater,int score,int userId) {
		// TODO: 2017/3/15  如果存在，就update 
		return new Rate().set("rater",rater).set("score",score).setStudent(userId).save();

	}

	public boolean updateRate(int id,int rater,int score,int userId) {
		return Rate.dao.findById(id).setRater(rater).setScore(score).setStudent(userId).update();
	}

	public boolean deleteRate(int id){
		return Rate.dao.findById(id).delete();
	}
}
