package com.demo.common.model;

import com.demo.common.model.base.BaseRate;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rate extends BaseRate<Rate> {
	public static final Rate dao = new Rate().dao();

	public List getRate(){
		return Rate.dao.find("select * from rate");
	}

	public boolean insertRate(int rater,int score,int userId) {

		List rateList = findStudent(rater,userId);
		if(rateList.size()>0){
			Rate r= (Rate) rateList.get(0);
			int id= r.getId();
			return updateRate(id,rater,score,userId);
		}else{
			return new Rate().set("rater",rater).set("score",score).setStudent(userId).save();
		}



	}

	public boolean updateRate(int id,int rater,int score,int userId) {
		return Rate.dao.findById(id).setRater(rater).setScore(score).setStudent(userId).update();
	}

	public boolean deleteRate(int id){
		return Rate.dao.findById(id).delete();
	}

	private List findStudent(int rater,int userId){
		return Rate.dao.find("select * from rate where rater = ? and student = ?",rater,userId);
	}


	public List getRateAvg(){
		return Rate.dao.find("select real_name,user_name,avg(score) as `score` from rate,student where rater=student.id group by rater");
	}
}
