package com.demo.common.model;

import com.demo.common.model.base.BaseRules;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rules extends BaseRules<Rules> {
    private static final Rules dao = new Rules().dao();

    public List getRules() {
        return Rules.dao.find("select * from rules");
    }

    public boolean insertRules(String rule) {
        return new Rules().set("rule", rule).save();
    }

    public boolean updateRules(int id,String rule) {
        return Rules.dao.findById(id).setRule(rule).update();
    }

    public boolean deleteRules(int id){
        return Rules.dao.findById(id).delete();
    }


}
