spring:
  datasource:
      url: jdbc:mysql://rm-wz9h86151kd3mlx1io.mysql.rds.aliyuncs.com:3306/quansheng?characterEncoding=utf8&useSSL=true
      username: zxmysql
      password: ZX123456zx!
      driverClassName: com.mysql.jdbc.Driver
#mybatis start
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.authentic.dao.entity
#mybatis end

