package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseHotelBook<M extends BaseHotelBook<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setHotel(java.lang.Integer hotel) {
		set("hotel", hotel);
		return (M)this;
	}

	public java.lang.Integer getHotel() {
		return get("hotel");
	}

	public M setVisitor(java.lang.Integer visitor) {
		set("visitor", visitor);
		return (M)this;
	}

	public java.lang.Integer getVisitor() {
		return get("visitor");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}

	public java.util.Date getTime() {
		return get("time");
	}

}
