package com.demo.common.model;

import com.demo.common.model.base.BaseHotelBook;

import java.util.Date;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HotelBook extends BaseHotelBook<HotelBook> {
	public static final HotelBook dao = new HotelBook().dao();
	
	public List getHotelBook(){
		return HotelBook.dao.find("select * from hotelBook");
	}

	public boolean insertHotelBook(int hotel,int visitor,String time) {
		return new HotelBook().set("hotel",hotel).set("visitor",visitor).set("time",time).save();
	}

	public boolean updateHotelBook(int id,int hotel,int visitor,Date time) {
		return HotelBook.dao.findById(id).setHotel(hotel).setVisitor(visitor).setTime(time).update();
	}

	public boolean deleteHotelBook(int id){
		return HotelBook.dao.findById(id).delete();
	}
}
