package com.demo.common.model;

import com.demo.common.model.base.BaseTravelNews;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TravelNews extends BaseTravelNews<TravelNews> {
	public static final TravelNews dao = new TravelNews().dao();
}
