package com.demo.common.model;

import com.demo.common.model.base.BaseTravelNews;

import java.util.Date;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TravelNews extends BaseTravelNews<TravelNews> {
	public static final TravelNews dao = new TravelNews().dao();
	public List getTravelNews(){
		return TravelNews.dao.find("select * from travel_news");
	}

	public boolean insertTravelNews(String title,String message,String pic,String time,int hotel) {
		return new TravelNews().set("title",title).set("message",message).set("pic",pic).set("time",time).set("hotel",hotel).save();
	}

	public boolean updateTravelNews(int id, String title, String message, String pic, Date time, int hotel) {
		return TravelNews.dao.findById(id).setTitle(title).setMessage(message).setPic(pic).setTime(time).setHotel(hotel).update();
	}

	public boolean deleteTravelNews(int id){
		return TravelNews.dao.findById(id).delete();
	}

	public List getTravelNewsById(int id) {
		return TravelNews.dao.find("select * from travel_news where hotel = ?", id);
	}
}

