package com.demo.common.model;

import com.demo.common.model.base.BaseViews;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Views extends BaseViews<Views> {
	public static final Views dao = new Views().dao();

	public List getViews(){
		return Views.dao.find("select * from views");
	}

	public boolean insertViews(String view,String message,String address,String pic) {
		return new Views().set("view",view).set("message",message).set("address",address).set("pic",pic).save();
	}

	public boolean updateViews(int id,String view,String message,String address,String pic) {
		return Views.dao.findById(id).setView(view).setMessage(message).setAddress(address).setPic(pic).update();
	}

	public boolean deleteViews(int id){
		return Views.dao.findById(id).delete();
	}
}
