package com.demo.common.model;

import com.demo.common.model.base.BaseViewHotel;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ViewHotel extends BaseViewHotel<ViewHotel> {
    public static final ViewHotel dao = new ViewHotel().dao();

    public List getViewHotel() {
        return ViewHotel.dao.find("select * from view_hotel");
    }

    public List getViewHotelById(int id) {
        return ViewHotel.dao.find("select * from view_hotel where view_id = ?", id);
    }

    public List getViewHotelByView(int view) {
        return ViewHotel.dao.find("select hotel.id,hotel.hotel_name,hotel.message,hotel.pic,x,y from view_hotel,hotel where view_id = ? and view_hotel.hotel_id=hotel.id", view);
    }

    public boolean insertViewHotel(int hotel_id, int view_id) {
        return new ViewHotel().set("hotel_id", hotel_id).set("view_id", view_id).save();
    }

    public boolean updateViewHotel(int id, int hotel_id, int view_id) {
        return ViewHotel.dao.findById(id).setHotelId(hotel_id).setViewId(view_id).update();
    }

    public boolean deleteViewHotel(int id) {
        return ViewHotel.dao.findById(id).delete();
    }

}
