package com.demo.common.model;

import com.demo.common.model.base.BaseViews;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Views extends BaseViews<Views> {
	public static final Views dao = new Views().dao();
}
