package com.demo.common.model;

import com.demo.common.model.base.BaseVisitor;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Visitor extends BaseVisitor<Visitor> {
	public static final Visitor dao = new Visitor().dao();

	public List getVisitor(){
		return Visitor.dao.find("select * from visitor");
	}

	public boolean insertVisitor(String user_name,String password,String phone) {
		return new Visitor().set("user_name",user_name).set("password",password).set("phone",phone).save();
	}

	public boolean updateVisitor(int id,String user_name,String password,String phone) {
		return Visitor.dao.findById(id).setUserName(user_name).setPassword(password).setPhone(phone).update();
	}

	public boolean deleteVisitor(int id){
		return Visitor.dao.findById(id).delete();
	}

	public List loginVisitor(String user,String password){
		return Visitor.dao.find("select * from visitor where user_name =? and password = ?",user,password);
	}

}
