package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseViewHotel<M extends BaseViewHotel<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setHotelId(java.lang.Integer hotelId) {
		set("hotel_id", hotelId);
		return (M)this;
	}

	public java.lang.Integer getHotelId() {
		return get("hotel_id");
	}

	public M setViewId(java.lang.Integer viewId) {
		set("view_id", viewId);
		return (M)this;
	}

	public java.lang.Integer getViewId() {
		return get("view_id");
	}

}
