package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseHotel<M extends BaseHotel<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setHotelName(java.lang.String hotelName) {
		set("hotel_name", hotelName);
		return (M)this;
	}

	public java.lang.String getHotelName() {
		return get("hotel_name");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public M setMessage(java.lang.String message) {
		set("message", message);
		return (M)this;
	}

	public java.lang.String getMessage() {
		return get("message");
	}

	public M setPic(java.lang.String pic) {
		set("pic", pic);
		return (M)this;
	}

	public java.lang.String getPic() {
		return get("pic");
	}

	public M setX(java.lang.String x) {
		set("x", x);
		return (M)this;
	}

	public java.lang.String getX() {
		return get("x");
	}

	public M setY(java.lang.String y) {
		set("y", y);
		return (M)this;
	}

	public java.lang.String getY() {
		return get("y");
	}

}
