package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRate<M extends BaseRate<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setRater(java.lang.Integer rater) {
		set("rater", rater);
		return (M)this;
	}

	public java.lang.Integer getRater() {
		return get("rater");
	}

	public M setscore(java.lang.Integer score) {
		set("score", score);
		return (M)this;
	}

	public java.lang.Integer getscore() {
		return get("score");
	}

}
