package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("hotel", "id", Hotel.class);
		arp.addMapping("hotel_book", "id", HotelBook.class);
		arp.addMapping("travel_news", "id", TravelNews.class);
		arp.addMapping("views", "id", Views.class);
		arp.addMapping("visitor", "id", Visitor.class);
	}
}

