package com.demo.common.model;

import com.demo.common.model.base.BaseHotel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Hotel extends BaseHotel<Hotel> {
	public static final Hotel dao = new Hotel().dao();
}
