package com.demo.common.model;

import com.demo.common.model.base.BaseHotelBook;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HotelBook extends BaseHotelBook<HotelBook> {
	public static final HotelBook dao = new HotelBook().dao();
}
